/* Generated by the Pascal-S compiler */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

    int result;

int addone(void);

int addone(void)
{
    int __pascc_ret_addone = 0;
    __pascc_ret_addone = (1 + 2);
    return __pascc_ret_addone;
}

int main(void)
{
    result = (addone() + 3);
    printf("%d", result);
    return 0;
}
