/* Generated by the Pascal-S compiler */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

    const int pi = 3;
    const int e = 2;
    int a;
    int b;

int main(void)
{
    b = 2;
    printf("%d", b);
    return 0;
}
