/* Generated by the Pascal-S compiler */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

    int a;

void inc1(int *x);

void inc1(int *x)
{
{
    *x = (*x + 1);
}
}

int main(void)
{
    a = 10;
    inc1(&a);
    printf("%d", a);
    return 0;
}
